apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swe
  name: swe
spec:
  replicas: 4
  selector:
    matchLabels:
      app: swe
  template:
    metadata:
      labels:
        app: swe
    spec:
      containers:
      - image: tuljabonam/swe645:latest
        name: swe
