apiVersion: v1
kind: Service
metadata:
  labels:
    app: swe
  name: swe
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: swe
  type: LoadBalancer
